# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171112_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='preview_image',
            new_name='preview',
        ),
    ]
