# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171112_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdisplayimage',
            name='attached_to',
            field=models.CharField(default='trew', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdisplayimage',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
