# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171112_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
