# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171113_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='TODO list for ebonsignori.com', max_length=500),
            preserve_default=False,
        ),
    ]
