# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('great', models.IntegerField(default=0)),
                ('good', models.IntegerField(default=0)),
                ('poor', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blog.Post')),
            ],
        ),
    ]
