# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171116_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/header_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='postdisplayimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/preview_images/%Y/%m/'),
        ),
    ]
