# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(max_length=500)),
                ('modal_body', models.TextField()),
                ('data_cat', models.CharField(max_length=500)),
                ('display_image', models.CharField(max_length=500)),
                ('display_image_alt_text', models.CharField(max_length=500)),
                ('caption_title', models.CharField(max_length=500)),
                ('caption_subtitle', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
