# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_acknowledgements'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='data_cat',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='display_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.PortfolioCategory'),
        ),
    ]
