# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171109_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='modal_client',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='modal_date',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='modal_header',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='modal_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='modal_subtitle',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='display_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
