# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171109_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgements',
            name='used_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgements',
            name='used_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
