# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171112_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
