# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_portfolioitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='display_image',
            field=models.ImageField(upload_to='home/portfolio/display_images/%Y/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='modal_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='home/portfolio/modal_images/%Y/'),
        ),
    ]
